### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by PlasmaMichael** [Ethatron/squish-ccr#2]
Hi,
I think writing a cmake script could be better to maintain the project, shouldn't took long time to write.
Second point is : Why use "Whole program optimization" on the visual studio project ?
I have to change to "No whole program optimization" to have the lib working on my project.
CMake set "No whole program optimization" when making the project too.

**Comment by Ethatron** [comment]
squish is a one-file include compile all library. Just include squish.cpp and be done. The VisualStudio project is only for getting started with the included samples.
