### ISSUE TITLE
Not compiled with pure C++ implementation.

### ISSUE THREAD

**Issue by juhl** [Ethatron/squish-ccr#3]
I want to compile with pure C++ implementation.
So I've added definition SQUISH_USE_CPP but some SSE functions are still being used.

**Comment by Ethatron** [comment]
The CPP define is only to select C++ vs. HLSL or AMP, not to disable SSE. I didn't update the SSE-less implementation in a long time.
The config.h contains the default selection for SQUISH_USE_SSE, which would be off.
