### ISSUE TITLE
Issue with DXT1 compression

### ISSUE THREAD

**Issue by yuhongyi** [Ethatron/squish-ccr#4]
Hello Ethatron,
    I'm having some issue with DXT1 compression using squish.  It seems that RGB channels are multiplied with alpha channel before they are compressed.  I did get your change which "fixed alpha-weighting for BC1", but it didn't work.  Do you already have a fix for this issue?

Thanks,
Hongyi

**Comment by Ethatron** [comment]
There is an option to configure weighting in squish.h: kWeightColourByAlpha
